---
output:
  html_document:
    code_folding: hide
    df_print: paged
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      cache = TRUE,
                      warning = FALSE, 
                      fig.align = "center")


library(dplyr)
library(stringr)

```


# MEDIAS ANEMOMETRO Y ERA5 PUNTO MAS CERCANO

```{r cols.print= 5, rows.print=3}

#CARGAMOS LOS DATOS DE ERA5 2018_2019
ERA5_df<- readRDS(here::here('NUEVO/Data_ERA5/ERA5_df.RDS'))


#CARGAMOS ANEMOS
#load(here::here("NUEVO/Data_anemometros/Anemometros.Rdata"))
#COJEMOS ANEMO UNI
#Anemometro_uni<- Anemometros$`0B38DAE79059`

DATOS_ANEMOMETRO_UNI<- readRDS(here::here('NUEVO/Data_calibracion/0B38DAE79059_juntos.rds')) %>% 
  .[,c(5,2,3,4)]
colnames(DATOS_ANEMOMETRO_UNI)<- c("Date", colnames(readRDS(here::here('NUEVO/Data_calibracion/0B38DAE79059_juntos.rds'))[,2:4]))

#CARGAMOS COORDENADAS DEL ANEMO
Coord_ERA5_anemo<- readRDS(here::here('NUEVO/Data_ERA5/ERA5_coord_0B38DAE79059.RDS'))

#CORTAMOS DATOS ERA PARA EL PUNTO MAS CERCANO. MC
ERA5_df_MC<- ERA5_df %>% dplyr::filter(., lon==Coord_ERA5_anemo$lon & lat==Coord_ERA5_anemo$lat) 
  
DATOS_JUNTOS<- left_join(DATOS_ANEMOMETRO_UNI, ERA5_df_MC, by="Date")


##### AÑADIMOS EL FACTOR K DEBIDO A LA ALTITUD
#Calculo factor K diferencia de modulo entre punto ERA y anemo
zo=3 #[m] Centers of cities with tall buildings - Manwell pag 46, tabla 2.2
z=155 + 3.5*6 + 1.5 #[m] Altura anemo = altitud segun google earth + altura edificio + altura poste anemo
zr=401 + 10 #[m] Altura era = altitud segun google earth + 10m
k=log(z/zo)/log(zr/zo)  #k=U(z)/U(zr)


###HACIENDO MEDIA DE LOS DATOS DE LOS ANEMOS. 
DATOS_JUNTOS %>% .[complete.cases(.),] %>% summarise(Anemo_mean=mean(Mean), Anemo_Gust=mean(Gust),
                                                     ERA5_mean=mean(uv_wind), ERA5_mean_K=mean(uv_wind*k))



#########HACIENDO MEDIAS DE LOS HISTÓRICOS DE ERA5



```

```{r cols.print= 5, rows.print=3}
# MEDIAS HISTORICAS ERA5 -------------------------------------------------

RDS_HISTORICO_ERA<-list.files(here::here('NUEVO/Data_ERA5/'), full.names = T) %>% 
  .[1:40]

ERA_mean<- vector()
#ERA_mean_k<- vector()

for (i in 1:length(RDS_HISTORICO_ERA) ) {
    ERA_mean[i]<- readRDS(RDS_HISTORICO_ERA[i]) %>% dplyr::filter(., lon==Coord_ERA5_anemo$lon & lat==Coord_ERA5_anemo$lat) %>% 
    summarise(ERA_mean= mean(uv_wind, na.rm = T))
    #ERA_mean_k[i]<- readRDS(RDS_HISTORICO_ERA[i]) %>% dplyr::filter(., lon==Coord_ERA5_anemo$lon & lat==Coord_ERA5_anemo$lat) %>%summarise(ERA_mean= mean(uv_wind*k, na.rm = T))
              
}
```

# MEDIAS ERA5 EN EL PUNTO MAS CERCANO EN TODO EL HISTORICO

```{r cols.print= 3, rows.print=40}
x<- RDS_HISTORICO_ERA %>% str_split("/") %>% lapply(., function(x) x[length(x)]) %>% 
  as.character() %>% str_remove_all("Data_|.RDS") %>% cbind(.,unlist(ERA_mean),unlist(ERA_mean)*k) %>% 
  as.data.frame()
colnames(x)<- c("Year", "Mean", "Mean_K")
x
```
```{r}
x %>% summarise(Mean_allyears=mean(as.numeric(as.character(Mean))),
                Mean_allyears_k=mean(as.numeric(as.character(Mean_K))))
```

