---
title: "MAPAS JONY"
author: "Oscar Garcia Hernandez"
date: "12/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE, 
                      warning = FALSE,
                      fig.align = 'center',
                      fig.height = 10,
                      fig.width = 10,
                      cache = TRUE)
```

```{r echo=FALSE}
library(here)
source(here::here('NUEVO/Libraries.R'))
```

# INTRO

Sin más, documento para dejar por escrito como se hacen mapas de relieve... emplearemos dos paquetes que a mi parecer estan muy de puta de madre... **elevatr** para obtener los rasters y **rasterVis** para plotearlos, ya que ofrece una manera sencilla de 

```{r}
library(elevatr)
library(rasterVis)
```

```{r eval=FALSE}
#IMPORTAMOS DATOS
DATOS_ANEMOS<- here::here('NUEVO/Data_calibracion/0B38DAE79059/ERA5_2019-03-01.RDS') %>% readRDS()


#HACEMOS TABLA DE PUNTOS DE ERA Y ANEMO 
long<- DATOS_ANEMOS$ERAlon %>% unique()
lat<- DATOS_ANEMOS$ERAlat %>% unique()

grid_ERA<- expand.grid(long, lat)
grid_ERA[, c("lon_A","lat_A")]<- c(rep(DATOS_ANEMOS$lon %>% unique(),nrow(grid_ERA)),
                                   rep(DATOS_ANEMOS$lat %>% unique(),nrow(grid_ERA)))

#AÑADIMOS DISTANCIAS A LA TABLA
vector_dist<- vector()
for (i in 1:nrow(grid_ERA)) {
  vector_dist[i]<- distm(c(grid_ERA$lon[i], grid_ERA$lat[i]),
                         c(grid_ERA$lon_A[i], grid_ERA$lat_A[i]))
  
}
grid_ERA$dist<- vector_dist
colnames(grid_ERA)<- c("lon", "lat", "lon_A", "lat_A", "dist")

P_selected<- grid_ERA


n=max(P_selected$lat)    
s=min(P_selected$lat)    
e=max(P_selected$lon)    
w=min(P_selected$lon) 

#AÑADIMIOS UN INCREMENTO Y UN ZOOM
# EL ZOOM VA DESDE 1 HASTA 14...
# OJITO, MÁS ZOOM, IMPLICA MÁS RESOLUCIÓN Y POR TANTO MAYOR PESO
incr<- 0.05
zoom_map<- 14

#Tengo que investigar más al respecto, pero creo que tiene relacion 
# directa con la resolución
# yo cuando pido un archivo tengo que pedirle el grid que quiero
# esta variable añade puntos al grid...
#Lo que no se es si añadiendo mas puntos se consigue mejorar la 
# resolución del raster
Point_number<- 50


if(n > 0){n<- n + incr}else{n<- n + incr}
if(s > 0){s<- s - incr}else{s<- s- incr}
if(e > 0){e<- e + incr}else{e<- e + incr}
if(w > 0){w<- w - incr}else{w<- w- incr}



ul <- round(c(n,w),digits = 8)  #Upper Left
lr <- round(c(s,e), digits = 8)  #Lower Right

#PONGO ESE IF DENTRO DEL BUCLE PORQUE TARDA LA VIDA
# Y SEGURAMENTE DESCARGARÉ LOS RASTERS DE VARIAS VECES...VARIOS DIAS

lon_location<- seq(lr[1],ul[1],length.out = Point_number ) 
lat_location<- seq(ul[2],lr[2], length.out = Point_number)
data_loc<- expand.grid(lat_location,lon_location)
colnames(data_loc)<- c("x", "y")

spdf <- SpatialPointsDataFrame(coords = data_loc, data = data_loc,
                               proj4string = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))


map_raster<- get_elev_raster(spdf, z=zoom_map)
  


#EXISTEN VARIAS PALETAS DE COLORES POR DEFECTO PARA PLOTEAR LOS 
# MAPAS
#magma, viridisTheme, infernoTheme, ç
#plasmaTheme, YlOrRdTheme, BuRdTheme, 
# RdBuTheme, GrTheme, BTCTheme)

levelplot(map_raster, par.settings= BTCTheme(), 
          contour=TRUE,
          interpolate=TRUE) + 
  layer(panel.points(grid_ERA$lon,
                     grid_ERA$lat,
                     pch=21, cex=2, 
                     colour='white', 
                     fill= 'white'))+
  layer(panel.points(grid_ERA$lon_A %>% unique(),
                     grid_ERA$lat_A %>% unique(),
                     pch=21, cex=2, 
                     colour='red', 
                     fill= 'red'))
```

```{r echo=FALSE}
DATOS_ANEMOS<- here::here('NUEVO/Data_calibracion/0B38DAE79059/ERA5_2019-03-01.RDS') %>% readRDS()


#HACEMOS TABLA DE PUNTOS DE ERA Y ANEMO 
long<- DATOS_ANEMOS$ERAlon %>% unique()
lat<- DATOS_ANEMOS$ERAlat %>% unique()

grid_ERA<- expand.grid(long, lat)
grid_ERA[, c("lon_A","lat_A")]<- c(rep(DATOS_ANEMOS$lon %>% unique(),nrow(grid_ERA)),
                                   rep(DATOS_ANEMOS$lat %>% unique(),nrow(grid_ERA)))

#AÑADIMOS DISTANCIAS A LA TABLA
vector_dist<- vector()
for (i in 1:nrow(grid_ERA)) {
  vector_dist[i]<- distm(c(grid_ERA$lon[i], grid_ERA$lat[i]),
                         c(grid_ERA$lon_A[i], grid_ERA$lat_A[i]))
  
}
grid_ERA$dist<- vector_dist
colnames(grid_ERA)<- c("lon", "lat", "lon_A", "lat_A", "dist")

map_raster1<-  here::here('NUEVO/Mapas/RastersRASTER_0B38DAE79059_0.05_12.RDS') %>% readRDS()


levelplot(map_raster1, par.settings= BTCTheme(), 
          contour=TRUE,
          interpolate=TRUE) + 
  layer(panel.points(grid_ERA$lon,
                     grid_ERA$lat,
                     pch=21, cex=2, 
                     colour='white', 
                     fill= 'white'))+
  layer(panel.points(grid_ERA$lon_A %>% unique(),
                     grid_ERA$lat_A %>% unique(),
                     pch=21, cex=2, 
                     colour='red', 
                     fill= 'red'))



levelplot(map_raster1, par.settings= BTCTheme(),
          interpolate=TRUE) + 
  layer(panel.points(grid_ERA$lon,
                     grid_ERA$lat,
                     pch=21, cex=1, 
                     colour='white', 
                     fill= 'white'))+
  layer(panel.points(grid_ERA$lon_A %>% unique(),
                     grid_ERA$lat_A %>% unique(),
                     pch=21, cex=1, 
                     colour='red', 
                     fill= 'red'))


```

# VARIAS PALETAS POR DEFECTO AUNQUE TAMBIEN SE PUEDEN PERSONALIZAR A NUESTRO GUSTO
```{r echo=FALSE}
#IMPORTAMOS DATOS
DATOS_ANEMOS<- here::here('NUEVO/Data_calibracion/0B38DAE79059/ERA5_2019-03-01.RDS') %>% readRDS()


#HACEMOS TABLA DE PUNTOS DE ERA Y ANEMO 
long<- DATOS_ANEMOS$ERAlon %>% unique()
lat<- DATOS_ANEMOS$ERAlat %>% unique()

grid_ERA<- expand.grid(long, lat)
grid_ERA[, c("lon_A","lat_A")]<- c(rep(DATOS_ANEMOS$lon %>% unique(),nrow(grid_ERA)),
                                   rep(DATOS_ANEMOS$lat %>% unique(),nrow(grid_ERA)))

#AÑADIMOS DISTANCIAS A LA TABLA
vector_dist<- vector()
for (i in 1:nrow(grid_ERA)) {
  vector_dist[i]<- distm(c(grid_ERA$lon[i], grid_ERA$lat[i]),
                         c(grid_ERA$lon_A[i], grid_ERA$lat_A[i]))
  
}
grid_ERA$dist<- vector_dist
colnames(grid_ERA)<- c("lon", "lat", "lon_A", "lat_A", "dist")

DOWNLOAD_ELEVATION_RASTER<- FALSE
if(DOWNLOAD_ELEVATION_RASTER){
  

#ESCOJEMOS LOS PUNTOS PARA DESCARGAR EL MAPA DE RELIEVE
PUNTO_MAS_CERCANO<- FALSE
if(PUNTO_MAS_CERCANO){
  P_selected<- grid_ERA[which.min(grid_ERA$dist),]
}else{
    P_selected<- grid_ERA
  }
n=max(P_selected$lat)    
s=min(P_selected$lat)    
e=max(P_selected$lon)    
w=min(P_selected$lon) 

#AÑADIMIOS UN INCREMENTO Y UN ZOOM
# EL ZOOM VA DESDE 1 HASTA 14...
# OJITO, MÁS ZOOM, IMPLICA MÁS RESOLUCIÓN Y POR TANTO MAYOR PESO
incr<- 0.007
zoom_map<- 14

#Tengo que investigar más al respecto, pero creo que tiene relacion 
# directa con la resolución
# yo cuando pido un archivo tengo que pedirle el grid que quiero
# esta variable añade puntos al grid...
#Lo que no se es si añadiendo mas puntos se consigue mejorar la 
# resolución del raster
Point_number<- 50


if(n > 0){n<- n + incr}else{n<- n + incr}
if(s > 0){s<- s - incr}else{s<- s- incr}
if(e > 0){e<- e + incr}else{e<- e + incr}
if(w > 0){w<- w - incr}else{w<- w- incr}



ul <- round(c(n,w),digits = 8)  #Upper Left
lr <- round(c(s,e), digits = 8)  #Lower Right


path_raster<- here::here('NUEVO/Mapas/Rasters/')
if(!dir.exists(path_raster)){dir.create(path_raster, 
                                        recursive = TRUE)}

#PONGO ESE IF DENTRO DEL BUCLE PORQUE TARDA LA VIDA
# Y SEGURAMENTE DESCARGARÉ LOS RASTERS DE VARIAS VECES...VARIOS DIAS

file_raster<- paste0(path_raster,"RASTER_0B38DAE79059_",incr,"_",
                     zoom_map,"_",ul[1] %>% round(4),"_",
                     lr[1] %>% round(4),".RDS")
if(file.exists(file_raster)){
  print("Este raster ya existe en: ", file_raster)
}else{
  
  lon_location<- seq(lr[1],ul[1],length.out = Point_number ) 
  lat_location<- seq(ul[2],lr[2], length.out = Point_number)
  data_loc<- expand.grid(lat_location,lon_location)
  colnames(data_loc)<- c("x", "y")
  
  spdf <- SpatialPointsDataFrame(coords = data_loc, data = data_loc,
                                 proj4string = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))
  
  
  map_raster<- get_elev_raster(spdf, z=zoom_map)
  saveRDS(map_raster, file_raster)
  
}

}

#EXISTEN VARIAS PALETAS DE COLORES POR DEFECTO PARA PLOTEAR LOS 
# MAPAS
#magma, viridisTheme, infernoTheme, ç
#plasmaTheme, YlOrRdTheme, BuRdTheme, 
# RdBuTheme, GrTheme, BTCTheme)


map_raster<- here::here('NUEVO/Mapas/Rasters/RASTER_0B38DAE79059_0.007_14_43.207_43.193.RDS') %>% readRDS()


levelplot(map_raster, par.settings= BTCTheme(), 
          contour= FALSE,
          interpolate=TRUE) + 
  layer(panel.points(grid_ERA$lon,
                     grid_ERA$lat,
                     pch=21, cex=2, 
                     colour='white', 
                     fill= 'white'))+
  layer(panel.points(grid_ERA$lon_A %>% unique(),
                     grid_ERA$lat_A %>% unique(),
                     pch=21, cex=2, 
                     colour='red', 
                     fill= 'red'))

map_raster<- here::here('NUEVO/Mapas/Rasters/RASTER_0B38DAE79059_0.007_14_43.207_43.193.RDS') %>% readRDS()
levelplot(map_raster, par.settings= magmaTheme(), 
          contour= FALSE,
          interpolate=TRUE) + 
  layer(panel.points(grid_ERA$lon,
                     grid_ERA$lat,
                     pch=21, cex=2, 
                     colour='white', 
                     fill= 'white'))+
  layer(panel.points(grid_ERA$lon_A %>% unique(),
                     grid_ERA$lat_A %>% unique(),
                     pch=21, cex=2, 
                     colour='red', 
                     fill= 'red'))

map_raster<- here::here('NUEVO/Mapas/Rasters/RASTER_0B38DAE79059_0.007_14_43.207_43.193.RDS') %>% readRDS()
levelplot(map_raster, par.settings= viridisTheme(), 
          contour= FALSE,
          interpolate=TRUE) + 
  layer(panel.points(grid_ERA$lon,
                     grid_ERA$lat,
                     pch=21, cex=2, 
                     colour='white', 
                     fill= 'white'))+
  layer(panel.points(grid_ERA$lon_A %>% unique(),
                     grid_ERA$lat_A %>% unique(),
                     pch=21, cex=2, 
                     colour='red', 
                     fill= 'red'))

map_raster<- here::here('NUEVO/Mapas/Rasters/RASTER_0B38DAE79059_0.007_14_43.207_43.193.RDS') %>% readRDS()
levelplot(map_raster, par.settings= infernoTheme(), 
          contour= FALSE,
          interpolate=TRUE) + 
  layer(panel.points(grid_ERA$lon,
                     grid_ERA$lat,
                     pch=21, cex=2, 
                     colour='white', 
                     fill= 'white'))+
  layer(panel.points(grid_ERA$lon_A %>% unique(),
                     grid_ERA$lat_A %>% unique(),
                     pch=21, cex=2, 
                     colour='red', 
                     fill= 'red'))

map_raster<- here::here('NUEVO/Mapas/Rasters/RASTER_0B38DAE79059_0.007_14_43.207_43.193.RDS') %>% readRDS()
levelplot(map_raster, par.settings= plasmaTheme(), 
          contour= FALSE,
          interpolate=TRUE) + 
  layer(panel.points(grid_ERA$lon,
                     grid_ERA$lat,
                     pch=21, cex=2, 
                     colour='white', 
                     fill= 'white'))+
  layer(panel.points(grid_ERA$lon_A %>% unique(),
                     grid_ERA$lat_A %>% unique(),
                     pch=21, cex=2, 
                     colour='red', 
                     fill= 'red'))
map_raster<- here::here('NUEVO/Mapas/Rasters/RASTER_0B38DAE79059_0.007_14_43.207_43.193.RDS') %>% readRDS()
levelplot(map_raster, par.settings= YlOrRdTheme(), 
          contour= FALSE,
          interpolate=TRUE) + 
  layer(panel.points(grid_ERA$lon,
                     grid_ERA$lat,
                     pch=21, cex=2, 
                     colour='white', 
                     fill= 'white'))+
  layer(panel.points(grid_ERA$lon_A %>% unique(),
                     grid_ERA$lat_A %>% unique(),
                     pch=21, cex=2, 
                     colour='red', 
                     fill= 'red'))
map_raster<- here::here('NUEVO/Mapas/Rasters/RASTER_0B38DAE79059_0.007_14_43.207_43.193.RDS') %>% readRDS()
levelplot(map_raster, par.settings= BuRdTheme(), 
          contour= FALSE,
          interpolate=TRUE) + 
  layer(panel.points(grid_ERA$lon,
                     grid_ERA$lat,
                     pch=21, cex=2, 
                     colour='white', 
                     fill= 'white'))+
  layer(panel.points(grid_ERA$lon_A %>% unique(),
                     grid_ERA$lat_A %>% unique(),
                     pch=21, cex=2, 
                     colour='red', 
                     fill= 'red'))
map_raster<- here::here('NUEVO/Mapas/Rasters/RASTER_0B38DAE79059_0.007_14_43.207_43.193.RDS') %>% readRDS()
levelplot(map_raster, par.settings= RdBuTheme(), 
          contour= FALSE,
          interpolate=TRUE) + 
  layer(panel.points(grid_ERA$lon,
                     grid_ERA$lat,
                     pch=21, cex=2, 
                     colour='white', 
                     fill= 'white'))+
  layer(panel.points(grid_ERA$lon_A %>% unique(),
                     grid_ERA$lat_A %>% unique(),
                     pch=21, cex=2, 
                     colour='red', 
                     fill= 'red'))
map_raster<- here::here('NUEVO/Mapas/Rasters/RASTER_0B38DAE79059_0.007_14_43.207_43.193.RDS') %>% readRDS()
levelplot(map_raster, par.settings=GrTheme(), 
          contour= FALSE,
          interpolate=TRUE) + 
  layer(panel.points(grid_ERA$lon,
                     grid_ERA$lat,
                     pch=21, cex=2, 
                     colour='white', 
                     fill= 'white'))+
  layer(panel.points(grid_ERA$lon_A %>% unique(),
                     grid_ERA$lat_A %>% unique(),
                     pch=21, cex=2, 
                     colour='red', 
                     fill= 'red'))

#LOCURA EN PROCESO
#plot3D(map_raster)


```



