---
title: "DIR CORRECTION USING OPENAIR??"
author: " Óscar García Hernández"
date: "22/5/2019"
output: 
  html_document

    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      cache = TRUE,
                      warning = FALSE, 
                      fig.align = "center")
library(ggplot2)
library(RNetCDF)
library(stringr)
library(lubridate)
library(request)
library(XML)
library(dplyr)
library(TTR)
library(data.table)
library(GGally)
library(e1071)
library(geosphere)
library(imputeTS)
```


```{r}

DATA_FOLDERS<- list.dirs(here::here('NUEVO/Data_calibracion/'), recursive = F)

DATOS_JUNTOS<- DATA_FOLDERS[1] %>% list.files(full.names = T) %>% 
  .[str_detect(., "ERA5")] %>% readRDS()


DATOS_JUNTOS_LISTA<- DATOS_JUNTOS %>% group_split(ERAlon,ERAlat)
#PLOTEOS PARA COMPROBAR SIMILITUD ENTRE ERA5 Y ANEMOMETRO

Tabla_dist<- DATOS_JUNTOS_LISTA %>% lapply(function(x){y<- cbind(x$ERAlon %>% unique, x$ERAlat %>% unique()) %>% as.data.frame(); colnames(y)<- c("lon","lat"); return(y)}) %>% sapply(., function(x){
  distm(x, c(DATOS_JUNTOS_LISTA[[1]]$lon %>% unique,
             DATOS_JUNTOS_LISTA[[1]]$lat %>% unique))
}) 

DATOS_PLOT<- DATOS_JUNTOS_LISTA[[which.min(Tabla_dist)]] %>%
  mutate(ERA_binDir= cut(ERAWD ,
                         breaks =c(0,seq(22.5,337.5,22.5),360, 361), 
                         labels = c(0,seq(22.5,337.5,22.5),0) %>% as.factor()))
DATOS_PLOT$ERA_binDir<- DATOS_PLOT$ERA_binDir %>% as.character() %>% as.numeric()

#FILTRADO POR DIRECCIONES
West<- c(247.5,270.0,292.5)
North_west<-c(292.5,315.0,337.5)
South_west<- c(202.5, 225.0, 247.5)
North<- c(0.0,22.5,337.5)
North_east<- c(22.5,45.0,67.5)
East<- c(67.5,90,112.5)
South_east<- c(112.5,135.0,157.5)
South<- c(135.0, 155.0,180.0, 202.5,225.0)

lista_dir<- list(West, North_east,North_west,
                 North, South, South_east,South_west,
                 East)

VEC_DIRS<- DATOS_PLOT$ERA_binDir %>% unique()
#Rosa de los vientos
#install.packages("openair")
library(openair)
for (i in 1:(length(VEC_DIRS)-1)) {
  DATOS_PLOT_fil<- DATOS_PLOT %>% filter( ERA_binDir%in%VEC_DIRS[i])

windRose(DATOS_PLOT_fil,
         ws="ERAWS",
         wd="ERA_binDir",
         paddle = F,
         ws.int = 0.25,
         breaks = round(max(DATOS_PLOT_fil$WS_N)/0.25),
         cols = "jet",
         key.position = "right",
         offset = 0.01,
         dig.lab = 1, main=paste("ERA5",VEC_DIRS[i]))
windRose(DATOS_PLOT_fil,
         ws="WS_N",
         wd="WD_N",
         paddle = F,
         ws.int = 0.25,
         breaks = round(max(DATOS_PLOT_fil$WS_N)/0.25),
         cols = "jet",
         key.position = "right",
         offset = 0.01,
         dig.lab = 1, main=paste("Anemometro",VEC_DIRS[i]))

pollutionRose(DATOS_PLOT_fil %>% mutate(WS_un=1, WS_dos=2),
         ws="WS_un",
         wd="ERA_binDir",
         ws2 ="WS_dos",
         wd2="WD_N", main=paste("COMPARATIVA",VEC_DIRS[i]))

  
}





```
